name: Custom Ubuntu Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install and run Neofetch
        run: |
          sudo apt update
          sudo apt install neofetch -y
          clear
          echo "Hello from GitHub actions!"
          neofetch
